name: student_project_lab_initiative_grp2
description: "Rebuilt UI from Figma"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI/Utility
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  device_preview: ^1.1.0
  http: ^1.2.0

  # Camera/Media (Using the higher version for camera_web)
  camera: ^0.11.2
  camera_web: ^0.3.5
  image_picker: ^1.2.0 # From Snippet 1

  # Location/File System
  path: ^1.9.0 # From Snippet 1
  path_provider: ^2.1.2 # From Snippet 2

  # Authentication (Using the newer major version)
  firebase_auth: ^5.0.0

  # State Persistence (Using the newer major version)
  shared_preferences: ^2.2.3

  # Permissions (From Snippet 1)
  permission_handler: ^11.3.1

  # Other Utilities (From Snippet 1)
  http_parser: ^4.0.2
  flutter_polygon: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700